<html>
<body>
<p>
<a href="https://github.com/laforge49/JActor2#readme">JActor2</a> &gt; <a href="../../index.html">Docs</a> &gt; <a href="../index.html">Tutorials</a> &gt; <a href="index.html">Core</a> &gt; StackOverflow
</p>
<h1>StackOverflow - The StackOverflow<i>Exception</i></h1>
<p>
When an uncaught StackOverflowError occurs while processing a request, a
<a href="../../api/org/agilewiki/jactor2/core/requests/StackOverflowException.html">StackOverflow<i>Exception</i></a>
is created and passed back to the source of the request.
This is demonstrated in the <a href="java7/StackOverflow.java">StackOverflow</a> program.
</p>
<pre>
</pre>
</body>
</html>
